/* 番种大全数据：每个番种一条（说明 + 示例牌型）
 * 示例牌型由 test/glossary.test.js 逐条校验，保证真的能算出该番种。
 * 记法：hand 暗手（含胡牌张），win 胡牌张，melds 副露，flags 事件，
 *       flowers 花牌，tile/win 都用牌谱记号（见 tiles.js）。
 */
(function (global) {
  'use strict';

  var DATA = {};

  DATA.mcr = {
    title: '国标麻将',
    unit: '番',
    intro: '中国麻将竞赛规则（1998）共 81 个番种，8 番起和，按「不重复原则」计分：番值高的番种已经包含低番种时，低番种不再重复计算。每条都配了一副能成立的示例牌型，可点「去算番」直接试算。',
    fans: [
      { name: '大四喜', value: 88, ex: 'mDaSiXi', desc: '东南西北四副风牌刻子（或杠）齐全，再加一对将牌。', tip: '不计三风刻、圈风刻、门风刻、碰碰和、幺九刻。' },
      { name: '大三元', value: 88, ex: 'mDaSanYuan', desc: '中、发、白三副刻子（或杠）齐全，再加一对将牌。', tip: '不计箭刻、双箭刻、幺九刻。' },
      { name: '绿一色', value: 88, ex: 'mLvYiSe', desc: '整副牌只由条子的 2、3、4、6、8 和发财组成（这些是绿色牌）。', tip: '不计清一色。' },
      { name: '九莲宝灯', value: 88, ex: 'mJiuLian', desc: '门清的清一色，由 1112345678999 加一张同花色牌组成。', tip: '不计清一色、门前清、幺九刻、连六、老少副、一般高、喜相逢。' },
      { name: '四杠', value: 88, ex: 'mSiGang', desc: '四副杠（明杠、暗杠都算），加一对将牌。', tip: '不计三杠、双明杠、双暗杠、明杠、暗杠、碰碰和、单钓将。' },
      { name: '连七对', value: 88, ex: 'mLianQiDui', desc: '七对且是同一花色连续的七个对子，如 11223344556677。', tip: '不计七对、清一色、一般高、喜相逢、无字、缺一门、单钓将。' },
      { name: '十三幺', value: 88, ex: 'mShiSanYao', desc: '十三种幺九牌各一张，其中一种成对，共 14 张。', tip: '不计混幺九、五门齐、门前清、单钓将、不求人。' },

      { name: '清幺九', value: 64, ex: 'mQingYaoJiu', desc: '全由序数牌 1、9 的刻子（或杠）与将牌组成，不含字牌。', tip: '不计混幺九、碰碰和、全带幺、幺九刻、无字、缺一门。' },
      { name: '小四喜', value: 64, ex: 'mXiaoSiXi', desc: '三副风牌刻子（或杠），第四种风牌作将。', tip: '不计三风刻。' },
      { name: '小三元', value: 64, ex: 'mXiaoSanYuan', desc: '中、发、白里有两副刻子（或杠），第三种作将。', tip: '不计箭刻、双箭刻。' },
      { name: '字一色', value: 64, ex: 'mZiYiSe', desc: '整副牌全部由字牌（风牌、三元牌）组成。', tip: '不计混幺九、碰碰和、全带幺、幺九刻、无字、缺一门、混一色。' },
      { name: '四暗刻', value: 64, ex: 'mSiAnKe', desc: '四副暗刻（或暗杠），加一对将牌。', tip: '不计碰碰和、门前清、不求人、三暗刻、双暗刻。' },
      { name: '一色双龙会', value: 64, ex: 'mYiSeShuangLong', desc: '同一花色的 123、123、789、789 四副顺子，加 5 作将。', tip: '不计清一色、平和、一般高、老少副。' },

      { name: '一色四同顺', value: 48, ex: 'mYiSeSiTongShun', desc: '同一花色四副完全相同的顺子。', tip: '不计一色三同顺、一般高、七对、清一色。' },
      { name: '一色四节高', value: 48, ex: 'mYiSeSiJieGao', desc: '同一花色四副依次递增一位的刻子，如 111、222、333、444。', tip: '不计一色三节高、碰碰和。' },

      { name: '一色四步高', value: 32, ex: 'mYiSeSiBuGao', desc: '同一花色四副依次递增一位或两位的顺子，如 123、234、345、456。', tip: '不计一色三步高、连六。' },
      { name: '三杠', value: 32, ex: 'mSanGang', desc: '三副杠（明杠、暗杠都算），加一副面子和一对将牌。', tip: '不计双明杠、双暗杠、明杠、暗杠、碰碰和。' },
      { name: '混幺九', value: 32, ex: 'mHunYaoJiu', desc: '全由字牌和序数牌 1、9 的刻子（或杠）与将牌组成。', tip: '不计碰碰和、全带幺、幺九刻。' },

      { name: '七对', value: 24, ex: 'mQiDui', desc: '七个对子，共 14 张。', tip: '不计单钓将、不求人、四归一。' },
      { name: '七星不靠', value: 24, ex: 'mQiXingBuKao', desc: '七种字牌各一张，另加三种花色中互不相靠的七张序数牌。', tip: '不计五门齐、门前清、不求人、全不靠。' },
      { name: '全双刻', value: 24, ex: 'mQuanShuangKe', desc: '全由序数牌 2、4、6、8 的刻子（或杠）和将牌组成。' },
      { name: '清一色', value: 24, ex: 'mQingYiSe', desc: '整副牌由同一种花色的序数牌组成。' },
      { name: '一色三同顺', value: 24, ex: 'mYiSeSanTongShun', desc: '同一花色三副完全相同的顺子。', tip: '不计一般高。' },
      { name: '一色三节高', value: 24, ex: 'mYiSeSanJieGao', desc: '同一花色三副依次递增一位的刻子，如 222、333、444。' },
      { name: '全大', value: 24, ex: 'mQuanDa', desc: '整副牌全由序数牌 7、8、9 组成。', tip: '不计无字。' },
      { name: '全中', value: 24, ex: 'mQuanZhong', desc: '整副牌全由序数牌 4、5、6 组成。', tip: '不计无字。' },
      { name: '全小', value: 24, ex: 'mQuanXiao', desc: '整副牌全由序数牌 1、2、3 组成。', tip: '不计无字。' },

      { name: '清龙', value: 16, ex: 'mQingLong', desc: '同一花色的 123、456、789 三副顺子连成一条龙。', tip: '不计连六、老少副、一般高、喜相逢。' },
      { name: '三色双龙会', value: 16, ex: 'mSanSeShuangLong', desc: '两种花色各有 123 与 789，第三种花色作 5 将。', tip: '不计喜相逢、老少副、无字、缺一门。' },
      { name: '一色三步高', value: 16, ex: 'mYiSeSanBuGao', desc: '同一花色三副依次递增一位或两位的顺子，如 123、234、345。', tip: '不计连六、老少副、一般高。' },
      { name: '全带五', value: 16, ex: 'mQuanDaiWu', desc: '每副面子和将牌里都有序数牌 5。', tip: '不计断幺。' },
      { name: '三同刻', value: 16, ex: 'mSanTongKe', desc: '三种花色、同一序数的刻子（或杠）各一副。', tip: '不计双同刻。' },
      { name: '三暗刻', value: 16, ex: 'mSanAnKe', desc: '三副暗刻（或暗杠）。', tip: '不计双暗刻。' },

      { name: '全不靠', value: 12, ex: 'mQuanBuKao', desc: '三种花色的 147、258、369 与字牌混在一起，任两张都不相靠，共 14 张。', tip: '不计五门齐、门前清、不求人。' },
      { name: '组合龙', value: 12, ex: 'mZuHeLong', desc: '三种花色的 147、258、369 各一组（共 9 张），再加一副面子和一对将牌。' },
      { name: '大于五', value: 12, ex: 'mDaYuWu', desc: '整副牌全由序数牌 6、7、8、9 组成。' },
      { name: '小于五', value: 12, ex: 'mXiaoYuWu', desc: '整副牌全由序数牌 1、2、3、4 组成。' },
      { name: '三风刻', value: 12, ex: 'mSanFengKe', desc: '三副风牌刻子（或杠）。' },

      { name: '花龙', value: 8, ex: 'mHuaLong', desc: '三种花色的 123、456、789 各一副，连成一条龙。' },
      { name: '推不倒', value: 8, ex: 'mTuiBuDao', desc: '全由牌面对称、倒过来看也一样的牌组成（1234589 饼、245689 条、白板）。' },
      { name: '三色三同顺', value: 8, ex: 'mSanSeSanTongShun', desc: '三种花色的同一序数顺子各一副。' },
      { name: '三色三节高', value: 8, ex: 'mSanSeSanJieGao', desc: '三种花色依次递增一位的刻子各一副，如 222 万、333 条、444 饼。' },
      { name: '无番和', value: 8, ex: 'mWuFanHe', desc: '和牌后数不出任何其他番种，按无番和计 8 番。' },
      { name: '妙手回春', value: 8, ex: 'mMiaoShou', desc: '自摸牌墙上的最后一张牌和牌。' },
      { name: '海底捞月', value: 8, ex: 'mHaiDi', desc: '和牌池里最后一张打出的牌。' },
      { name: '杠上开花', value: 8, ex: 'mGangShangKaiHua', desc: '开杠后补摸的那张牌恰好和牌。' },
      { name: '抢杠和', value: 8, ex: 'mQiangGang', desc: '和别家开杠的那张牌。' },

      { name: '碰碰和', value: 6, ex: 'mPengPengHe', desc: '四副刻子（或杠）加一对将牌。' },
      { name: '混一色', value: 6, ex: 'mHunYiSe', desc: '一种花色的序数牌，加上字牌。' },
      { name: '三色三步高', value: 6, ex: 'mSanSeSanBuGao', desc: '三种花色依次递增一位的顺子各一副，如 123 万、234 条、345 饼。' },
      { name: '五门齐', value: 6, ex: 'mWuMenQi', desc: '万、条、饼、风牌、三元牌五门齐全。' },
      { name: '全求人', value: 6, ex: 'mQuanQiuRen', desc: '四副副露，单吊将牌，靠别家点炮和牌。' },
      { name: '双箭刻', value: 6, ex: 'mShuangJianKe', desc: '中、发、白里的两副刻子（或杠）。', tip: '不计箭刻。' },

      { name: '全带幺', value: 4, ex: 'mQuanDaiYao', desc: '每副面子和将牌都带幺九牌（1、9 或字牌）。', tip: '不计幺九刻。' },
      { name: '不求人', value: 4, ex: 'mBuQiuRen', desc: '门清状态下自摸和牌。', tip: '不计自摸、门前清。' },
      { name: '双明杠', value: 4, ex: 'mShuangMingGang', desc: '两副明杠。' },
      { name: '双暗杠', value: 8, ex: 'mShuangAnGang', desc: '两副暗杠。' },
      { name: '和绝张', value: 4, ex: 'mHeJueZhang', desc: '和的那张牌在桌面已经见过三张。' },

      { name: '箭刻', value: 2, ex: 'mJianKe', desc: '中、发、白任意一种的刻子（或杠）。' },
      { name: '圈风刻', value: 2, ex: 'mQuanFengKe', desc: '与圈风相同的风牌刻子（或杠）。' },
      { name: '门风刻', value: 2, ex: 'mMenFengKe', desc: '与门风（自风）相同的风牌刻子（或杠）。' },
      { name: '门前清', value: 2, ex: 'mMenQianQing', desc: '没有副露，靠别家点炮和牌。' },
      { name: '平和', value: 2, ex: 'mPingHe', desc: '四副顺子加序数牌将牌，没有刻子。', tip: '不计无字。' },
      { name: '四归一', value: 2, ex: 'mSiGuiYi', desc: '四张相同的牌分散在两副面子里（不是杠）。' },
      { name: '双同刻', value: 2, ex: 'mShuangTongKe', desc: '两种花色、同一序数的刻子（或杠）各一副。' },
      { name: '双暗刻', value: 2, ex: 'mShuangAnKe', desc: '两副暗刻（或暗杠）。' },
      { name: '暗杠', value: 2, ex: 'mAnGang', desc: '一副暗杠。' },
      { name: '断幺', value: 2, ex: 'mDuanYao', desc: '整副牌只有序数牌 2 到 8，没有幺九和字牌。', tip: '不计无字。' },

      { name: '一般高', value: 1, ex: 'mYiBanGao', desc: '两副完全相同的顺子。' },
      { name: '喜相逢', value: 1, ex: 'mXiXiangFeng', desc: '两种花色、同一序数的顺子各一副。' },
      { name: '连六', value: 1, ex: 'mLianLiu', desc: '同一花色两副相连的顺子，如 123 与 456。' },
      { name: '老少副', value: 1, ex: 'mLaoshaoFu', desc: '同一花色的 123 与 789。' },
      { name: '幺九刻', value: 1, variable: true, valueText: '1/组', ex: 'mYaoJiuKe', desc: '幺九牌（1、9 或字牌）的刻子（或杠），一组算 1 番，可以累计。' },
      { name: '明杠', value: 1, ex: 'mMingGang', desc: '一副明杠。' },
      { name: '缺一门', value: 1, ex: 'mQueYiMen', desc: '整副牌少一种花色。' },
      { name: '无字', value: 1, ex: 'mWuZi', desc: '整副牌没有字牌。' },
      { name: '边张', value: 1, ex: 'mBianZhang', desc: '单等边上的 3（12 等 3）或 7（89 等 7）。' },
      { name: '坎张', value: 1, ex: 'mKanZhang', desc: '和顺子中间的那张，如 13 等 2。' },
      { name: '单钓将', value: 1, ex: 'mDanDiaoJiang', desc: '单吊一张将牌和牌。' },
      { name: '自摸', value: 1, ex: 'mZiMo', desc: '自己摸到和牌张。' },
      { name: '花牌', value: 1, variable: true, valueText: '1/张', ex: 'mHuaPai', desc: '春夏秋冬梅兰竹菊，每张花牌 1 番。' }
    ],
    examples: {
      mDaSiXi: { hand: '东东东南南南西西西北北北五万五万', win: '5m', note: '四副风刻 + 5 万将' },
      mDaSanYuan: { hand: '中中中发发发白白白234m55s', win: '2m', note: '三副箭刻 + 234m + 55s 将' },
      mLvYiSe: { hand: '234s234s666s发发发88s', win: '4s', note: '条子的绿色牌加发财' },
      mJiuLian: { hand: '11123445678999m', win: '4m', note: '111 + 234 + 456 + 789 + 99，胡 4 万' },
      mSiGang: { hand: '中中', win: '中', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '9s' }, { type: 'kan', tile: '5p' }, { type: 'kan', tile: '东' }], note: '四副杠 + 中中将' },
      mLianQiDui: { hand: '11223344556677m', win: '1m', note: '同花色连续七个对子' },
      mShiSanYao: { hand: '19m19s19p东南西北中发白1m', win: '9m', note: '十三种幺九牌各一张 + 一张 1 万成对' },

      mQingYaoJiu: { hand: '111m999m111s999s99p', win: '1m', note: '全是 1、9 的刻子与将牌' },
      mXiaoSiXi: { hand: '东东东南南南西西西北北234m', win: '2m', note: '东、南、西三副风刻，北作将' },
      mXiaoSanYuan: { hand: '中中中发发发白白234m567s', win: '2m', note: '中、发刻子，白作将' },
      mZiYiSe: { hand: '东东东南南南西西西中中中发发', win: '东', note: '全字牌：三副风刻 + 中刻 + 发作将' },
      mSiAnKe: { hand: '111m333m555m777m99m', win: '1m', tsumo: true, note: '自摸，四副暗刻' },
      mYiSeShuangLong: { hand: '123m123m789m789m55m', win: '5m', note: '清一色 123、123、789、789 + 5 万将' },

      mYiSeSiTongShun: { hand: '123m55m', melds: [{ type: 'chi', tile: '1m' }, { type: 'chi', tile: '1m' }, { type: 'chi', tile: '1m' }], win: '5m', note: '吃了三副 123 万，手里再补一副' },
      mYiSeSiJieGao: { hand: '111m222m333m444m55m', win: '3m', note: '四副依次递增一位的刻子' },

      mYiSeSiBuGao: { hand: '123m234m345m456m55m', win: '4m', note: '四副依次递增一位的顺子' },
      mSanGang: { hand: '234p55p', win: '2p', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '9s' }, { type: 'kan', tile: '东' }], note: '三副杠 + 234 饼 + 55 饼将' },
      mHunYaoJiu: { hand: '111m999s中中中东东东白白', win: '东', note: '字牌与 1、9 的刻子、将牌' },

      mQiDui: { hand: '1122m3344s5566p东东', win: '东', note: '七个对子' },
      mQiXingBuKao: { hand: '147m25s36p东南西北中发白', win: '7m', note: '七种字牌齐全 + 互不相靠的七张序数牌' },
      mQuanShuangKe: { hand: '222m222s666m666s88p', win: '2m', note: '全是 2、4、6、8 的刻子与将牌' },
      mQingYiSe: { hand: '123m456m789m123m55m', win: '9m', note: '整副牌只有万子' },
      mYiSeSanTongShun: { hand: '123m123m123m456s55s', win: '2m', note: '三副一模一样的 123 万' },
      mYiSeSanJieGao: { hand: '222m333m555m99m', melds: [{ type: 'pon', tile: '1m' }], win: '9m', note: '碰 1 万，手里 2、3、5 万三副刻子' },
      mQuanDa: { hand: '777m888m999m789s77s', win: '7m', note: '只有 7、8、9' },
      mQuanZhong: { hand: '444m555m666m456s55s', win: '4m', note: '只有 4、5、6' },
      mQuanXiao: { hand: '111m222m333m123s22s', win: '1m', note: '只有 1、2、3' },

      mQingLong: { hand: '123m456m789m111m99m', win: '2m', note: '万子的 123、456、789 连成一条龙' },
      mSanSeShuangLong: { hand: '123s789s123p789p55m', win: '1s', note: '条、饼各有一头一尾，5 万作将' },
      mYiSeSanBuGao: { hand: '123m234m345m456s55s', win: '2m', note: '万子三副依次递增一位的顺子' },
      mQuanDaiWu: { hand: '345m567m555s456p55p', win: '3m', note: '每副面子和将牌都有 5' },
      mSanTongKe: { hand: '111m111s111p456m99m', win: '4m', note: '万、条、饼各一副 1 的刻子' },
      mSanAnKe: { hand: '111m333m555m99m', melds: [{ type: 'chi', tile: '1s' }], win: '9m', note: '吃 123 条，手里三副暗刻' },

      mQuanBuKao: { hand: '147m258s369p东南西北中', win: '7m', note: '花色内隔三、字牌不重复，互不相靠' },
      mZuHeLong: { hand: '147m258s369p中中中55m', win: '1m', note: '三种花色的 147、258、369 + 中刻 + 55 万将' },
      mDaYuWu: { hand: '666m777m888p999s77s', win: '6m', note: '只有 6 以上的牌' },
      mXiaoYuWu: { hand: '111m222m333p444s22s', win: '1m', note: '只有 4 以下的牌' },
      mSanFengKe: { hand: '东东东南南南西西西234m55s', win: '2m', note: '东、南、西三副风刻' },

      mHuaLong: { hand: '123m456s789p中中中55m', win: '1m', note: '万 123、条 456、饼 789 连成花龙' },
      mTuiBuDao: { hand: '123p234p789p888p55p', win: '2p', note: '饼子的对称牌 + 5 饼将，倒过来看也一样' },
      mSanSeSanTongShun: { hand: '123m123s123p456s55s', win: '1m', note: '三种花色各一副 123' },
      mSanSeSanJieGao: { hand: '111m222s333p456m99m', win: '1m', note: '万 111、条 222、饼 333 依次递增' },
      mWuFanHe: { hand: '567m345s789p中中', melds: [{ type: 'chi', tile: '1m' }], win: '5m', note: '吃 123 万，其余全顺子，数不出任何番种' },
      mMiaoShou: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { haitei: true }, note: '自摸墙上最后一张' },
      mHaiDi: { hand: '123m456m789m123s55s', win: '9m', flags: { houtei: true }, note: '和牌池里最后一张打出的牌' },
      mGangShangKaiHua: { hand: '234m567m789s99s', melds: [{ type: 'kan', tile: '1m' }], win: '9s', tsumo: true, flags: { rinshan: true }, note: '杠后补摸 9 条成和' },
      mQiangGang: { hand: '123m456m789m123s55s', win: '9m', flags: { chankan: true }, note: '抢了别家加杠的那张牌' },

      mPengPengHe: { hand: '111m333m555m777m99m', win: '1m', note: '四副刻子 + 99 万将' },
      mHunYiSe: { hand: '123m456m789m中中中99m', win: '2m', note: '只有万子和字牌' },
      mSanSeSanBuGao: { hand: '123m234s345p456s55s', win: '2m', note: '万 123、条 234、饼 345 依次递增' },
      mWuMenQi: { hand: '123m456s789p中中中东东', win: '2m', note: '万、条、饼、风、箭五门齐全' },
      mQuanQiuRen: { hand: '55p', win: '5p', melds: [{ type: 'chi', tile: '1m' }, { type: 'chi', tile: '4s' }, { type: 'pon', tile: '东' }, { type: 'pon', tile: '中' }], note: '四副副露，单吊 5 饼等点炮' },
      mShuangJianKe: { hand: '中中中发发发234m567s88s', win: '2m', note: '中、发两副刻子' },

      mQuanDaiYao: { hand: '123m789m111s999s中中', win: '2m', note: '每副面子和将牌都带幺九' },
      mBuQiuRen: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, note: '门清自摸' },
      mShuangMingGang: { hand: '234m567m88m', win: '8m', melds: [{ type: 'kan', tile: '东' }, { type: 'kan', tile: '中' }], note: '东、中两副明杠' },
      mHeJueZhang: { hand: '123m456m789m123s55s', win: '5s', flags: { lastTile: true }, note: '5 条已经见过三张，和绝张' },

      mJianKe: { hand: '中中中123m456m789s55s', win: '2m', note: '一副中刻' },
      mQuanFengKe: { hand: '东东东123m456m789s55s', win: '2m', roundWind: 0, seatWind: 1, note: '东圈，东风刻' },
      mMenFengKe: { hand: '南南南123m456m789s55s', win: '2m', roundWind: 0, seatWind: 1, note: '南家，南风刻' },
      mMenQianQing: { hand: '123m456m789m123m55m', win: '9m', note: '门清点炮和牌' },
      mPingHe: { hand: '123m456m789m123s55s', win: '9m', note: '四副顺子 + 5 条将' },
      mSiGuiYi: { hand: '111m123m456m789m99m', win: '9m', note: '四张 1 万分散在刻子与顺子里' },
      mShuangTongKe: { hand: '111m111s555m555s99m', win: '1m', note: '1 万、5 万在两种花色里各成刻' },
      mShuangAnKe: { hand: '111m333m456m789m99m', win: '9m', note: '111 万、333 万两副暗刻' },
      mAnGang: { hand: '234m567m789m99m', win: '9m', melds: [{ type: 'ankan', tile: '东' }], roundWind: 0, seatWind: 1, note: '暗杠东风' },
      mDuanYao: { hand: '234m567m345s678p55p', win: '2m', note: '只有 2 到 8 的序数牌' },

      mYiBanGao: { hand: '123m123m567m789m55m', win: '5m', note: '两副相同的 123 万' },
      mXiXiangFeng: { hand: '123m123s123p456s55s', win: '2m', note: '万、条（还有饼）都是同点数的 123' },
      mLianLiu: { hand: '123m456m234m234m55m', win: '1m', note: '123 万与 456 万相连' },
      mLaoshaoFu: { hand: '123m789m234m567m55m', win: '1m', note: '123 万与 789 万老少配' },
      mYaoJiuKe: { hand: '111m234m567m中中中99m', win: '9m', note: '1 万刻子和中刻都算幺九刻，这副牌有两组' },
      mMingGang: { hand: '234m567m789m99m', win: '9m', melds: [{ type: 'kan', tile: '东' }], roundWind: 0, seatWind: 1, note: '明杠东风' },
      mQueYiMen: { hand: '中中中123m456m111s99s', win: '2m', note: '只有万、条两门，缺饼子' },
      mWuZi: { hand: '123p234p789p888p55p', win: '2p', note: '整副没有字牌' },
      mShuangAnGang: { hand: '234p567p88p', win: '2p', melds: [{ type: 'ankan', tile: '1m' }, { type: 'ankan', tile: '9s' }], note: '暗杠 1 万和 9 条' },
      mBianZhang: { hand: '123m123m789m789m55m', win: '3m', note: '12 万等 3 万，边张' },
      mKanZhang: { hand: '123m234m567m789m55m', win: '2m', note: '13 万等 2 万，坎张' },
      mDanDiaoJiang: { hand: '123m456m789m中中中99m', win: '9m', note: '单吊 9 万将' },
      mZiMo: { hand: '456m789s234p中中', melds: [{ type: 'chi', tile: '1m' }], win: '4m', tsumo: true, note: '自己摸到 4 万' },
      mHuaPai: { hand: '123m456m789m123s55s', win: '9m', flowers: ['f1', 'f2'], note: '摸到春、夏两张花牌' }
    }
  };

  DATA.riichi = {
    title: '日本立直麻将',
    unit: '番',
    intro: '日麻看「役」：没有役不能和牌（宝牌不算役）。役满固定 13 番，普通役按番数加符数换算点数，门清与副露的番数可能不同（食い下がり）。',
    fans: [
      { name: '国士无双', value: 13, ex: 'rGuoShi', desc: '十三种幺九牌各一张，其中一种成对，共 14 张。' },
      { name: '国士无双十三面', value: 13, ex: 'rGuoShi13', desc: '国士无双的十三面听形态：和牌前正好十三种各一张，听十三种牌。' },
      { name: '四暗刻', value: 13, ex: 'rSiAnKe', desc: '四副暗刻（或暗杠），加一对将牌。' },
      { name: '四暗刻单骑', value: 13, ex: 'rSiAnKeDanQi', desc: '四暗刻并且单骑听牌和牌。' },
      { name: '大三元', value: 13, ex: 'rDaSanYuan', desc: '中、发、白三副刻子（或杠）齐全。' },
      { name: '大四喜', value: 13, ex: 'rDaSiXi', desc: '东南西北四副风牌刻子（或杠）齐全。' },
      { name: '小四喜', value: 13, ex: 'rXiaoSiXi', desc: '三副风牌刻子（或杠），第四种风牌作将。' },
      { name: '字一色', value: 13, ex: 'rZiYiSe', desc: '整副牌全部由字牌组成。' },
      { name: '绿一色', value: 13, ex: 'rLvYiSe', desc: '整副牌只由条子的 2、3、4、6、8 和发财组成。' },
      { name: '清老头', value: 13, ex: 'rQingLaoTou', desc: '整副牌全部由序数牌 1、9 的刻子（或杠）与将牌组成。' },
      { name: '四槓子', value: 13, ex: 'rSiGangZi', desc: '四副杠，加一对将牌。' },
      { name: '九莲宝灯', value: 13, ex: 'rJiuLian', desc: '门清清一色的 1112345678999 形，和任意一张同花色牌。' },
      { name: '纯正九莲宝灯', value: 13, ex: 'rJiuLianPure', desc: '九莲宝灯中和牌前正好是 1112345678999 的九面听形态。' },
      { name: '天和', value: 13, ex: 'rTenhou', desc: '庄家配牌后立刻自摸和牌。' },
      { name: '地和', value: 13, ex: 'rChiihou', desc: '子家第一巡自摸和牌（牌山未被鸣牌改变）。' },

      { name: '立直', value: 1, ex: 'rRiichi', desc: '门听状态下宣告立直并和牌。' },
      { name: '两立直', value: 2, ex: 'rDoubleRiichi', desc: '第一巡就宣告立直。' },
      { name: '一发', value: 1, ex: 'rIppatsu', desc: '立直后一巡内和牌，期间无人鸣牌。' },
      { name: '门前清自摸和', value: 1, ex: 'rMenzenTsumo', desc: '门清状态下自摸和牌。' },
      { name: '平和', value: 1, ex: 'rPinfu', desc: '门清、四副顺子、非役牌将牌、两面听。' },
      { name: '断幺九', value: 1, ex: 'rTanyao', desc: '整副牌只有序数牌 2 到 8。' },
      { name: '一盃口', value: 1, ex: 'rIipeikou', desc: '门清状态下有两副完全相同的顺子。' },
      { name: '二盃口', value: 3, ex: 'rRyangpeikou', desc: '门清状态下有两组相同的顺子（共四副）。' },
      { name: '三色同顺', value: 2, valueText: '门清 2 / 副露 1', ex: 'rSanshokuDoujun', desc: '三种花色同一序数的顺子各一副。' },
      { name: '一气通贯', value: 2, valueText: '门清 2 / 副露 1', ex: 'rIttsu', desc: '同一花色的 123、456、789 三副顺子。' },
      { name: '三色同刻', value: 2, ex: 'rSanshokuDoukou', desc: '三种花色同一序数的刻子（或杠）各一副。' },
      { name: '三暗刻', value: 2, ex: 'rSanankou', desc: '三副暗刻（或暗杠）。' },
      { name: '三槓子', value: 2, ex: 'rSankantsu', desc: '三副杠。' },
      { name: '对对和', value: 2, ex: 'rToitoi', desc: '四副刻子（或杠）加一对将牌。' },
      { name: '小三元', value: 2, ex: 'rShousangen', desc: '中、发、白里有两副刻子，第三种作将。' },
      { name: '混全带幺九', value: 2, valueText: '门清 2 / 副露 1', ex: 'rChanta', desc: '每副面子和将牌都带幺九牌，且有字牌。' },
      { name: '纯全带幺九', value: 3, valueText: '门清 3 / 副露 2', ex: 'rJunchan', desc: '每副面子和将牌都带幺九牌，且没有字牌。' },
      { name: '混老头', value: 2, ex: 'rHonroutou', desc: '整副牌全部由幺九牌和字牌组成。' },
      { name: '七对子', value: 2, ex: 'rChiitoitsu', desc: '七个对子，共 14 张。' },
      { name: '清一色', value: 6, valueText: '门清 6 / 副露 5', ex: 'rChinitsu', desc: '整副牌由同一种花色的序数牌组成。' },
      { name: '混一色', value: 3, valueText: '门清 3 / 副露 2', ex: 'rHonitsu', desc: '一种花色的序数牌加字牌。' },
      { name: '役牌（中/发/白）', value: 1, alts: ['役牌 中', '役牌 发', '役牌 白'], ex: 'rYakuhai', desc: '中、发、白任意一种的刻子（或杠），每种各计 1 番。' },
      { name: '场风（东/南/西/北）', value: 1, alts: ['场风 东', '场风 南', '场风 西', '场风 北'], ex: 'rBakaze', desc: '与场风相同的风牌刻子（或杠）。' },
      { name: '自风（东/南/西/北）', value: 1, alts: ['自风 东', '自风 南', '自风 西', '自风 北'], ex: 'rJikaze', desc: '与自风相同的风牌刻子（或杠）。' },
      { name: '宝牌', value: 1, variable: true, valueText: '每张 +1 番', ex: 'rDora', desc: '每张宝牌加 1 番；宝牌不算役，不能靠它起和。' },
      { name: '里宝牌', value: 1, variable: true, valueText: '每张 +1 番', ex: 'rUraDora', desc: '立直和牌后翻开的里宝牌，每张加 1 番。' },
      { name: '岭上开花', value: 1, ex: 'rRinshan', desc: '开杠后补摸的牌自摸和牌。' },
      { name: '抢槓', value: 1, ex: 'rChankan', desc: '和别家加杠的那张牌。' },
      { name: '海底摸月', value: 1, ex: 'rHaitei', desc: '自摸牌墙上的最后一张牌和牌。' },
      { name: '河底捞鱼', value: 1, ex: 'rHoutei', desc: '和牌池里最后一张打出的牌。' }
    ],
    examples: {
      rGuoShi: { hand: '119m19s19p东南西北中发白', win: '9m', note: '十三种幺九牌齐全，1 万成对' },
      rGuoShi13: { hand: '19m19s19p东南西北中发白1m', win: '1m', note: '和牌前正好十三种各一张' },
      rSiAnKe: { hand: '111m333m555m777m99m', win: '1m', tsumo: true, note: '自摸，四副暗刻' },
      rSiAnKeDanQi: { hand: '111m333m555m777m99m', win: '9m', note: '四暗刻单骑 9 万' },
      rDaSanYuan: { hand: '中中中发发发白白白234m55s', win: '2m', note: '三副箭刻' },
      rDaSiXi: { hand: '东东东南南南西西西北北北55m', win: '5m', note: '四副风刻' },
      rXiaoSiXi: { hand: '东东东南南南西西西北北234m', win: '2m', note: '三副风刻，北作将' },
      rZiYiSe: { hand: '东东东南南南西西西中中中发发', win: '东', note: '全字牌' },
      rLvYiSe: { hand: '234s234s666s发发发88s', win: '4s', note: '条子的绿色牌加发财' },
      rQingLaoTou: { hand: '111m999m111s999s99p', win: '1m', note: '全是 1、9 的刻子与将牌' },
      rSiGangZi: { hand: '中中', win: '中', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '9s' }, { type: 'kan', tile: '5p' }, { type: 'kan', tile: '东' }], note: '四副杠 + 中中将' },
      rJiuLian: { hand: '11122345678999m', win: '1m', note: '九莲形，和 1 万' },
      rJiuLianPure: { hand: '11123456789995m', win: '5m', note: '和牌前正好 1112345678999，九面听' },
      rTenhou: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { tenhou: true }, note: '庄家配牌即自摸' },
      rChiihou: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { chiihou: true }, note: '子家第一巡自摸' },

      rRiichi: { hand: '123m456m789m123s55s', win: '9m', flags: { riichi: true }, note: '立直后和 9 万' },
      rDoubleRiichi: { hand: '123m456m789m123s55s', win: '9m', flags: { riichi: true, doubleRiichi: true }, note: '第一巡立直' },
      rIppatsu: { hand: '123m456m789m123s55s', win: '9m', flags: { riichi: true, ippatsu: true }, note: '立直后一巡内和牌' },
      rMenzenTsumo: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, note: '门清自摸' },
      rPinfu: { hand: '123m456m789m123s55s', win: '9m', note: '四顺子 + 非役牌将牌，两面听' },
      rTanyao: { hand: '234m567m345s678p55p', win: '2m', note: '只有 2 到 8' },
      rIipeikou: { hand: '123m123m456s789s55s', win: '2m', note: '两副相同的 123 万' },
      rRyangpeikou: { hand: '123m123m456s456s55s', win: '2m', note: '两组相同顺子' },
      rSanshokuDoujun: { hand: '123m123s123p456s55s', win: '1m', note: '三种花色各一副 123' },
      rIttsu: { hand: '123m456m789m456s55s', win: '1m', note: '万子的 123、456、789' },
      rSanshokuDoukou: { hand: '111m111s111p456m99m', win: '9m', note: '三种花色各一副 1 的刻子' },
      rSanankou: { hand: '111m333m555m99m', melds: [{ type: 'chi', tile: '1s' }], win: '9m', note: '吃 123 条，手里三副暗刻' },
      rSankantsu: { hand: '234p55p', win: '2p', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '9s' }, { type: 'kan', tile: '东' }], note: '三副杠' },
      rToitoi: { hand: '111m333m555m777m99m', win: '1m', note: '四副刻子' },
      rShousangen: { hand: '中中中发发发白白234m567s', win: '2m', note: '中、发刻子，白作将' },
      rChanta: { hand: '123m789m111s999s东东', win: '1m', note: '每副面子和将牌都带幺九' },
      rJunchan: { hand: '123m789m111s999s99p', win: '1m', note: '每副面子和将牌都带幺九，没有字牌' },
      rHonroutou: { hand: '111m999m111s999s东东', win: '1m', note: '全幺九与字牌' },
      rChiitoitsu: { hand: '1122m3344s5566p东东', win: '东', note: '七个对子' },
      rChinitsu: { hand: '123m456m789m123m55m', win: '9m', note: '全万子' },
      rHonitsu: { hand: '123m456m789m中中中99m', win: '2m', note: '万子加字牌' },
      rYakuhai: { hand: '中中中123m456m789s55s', win: '2m', note: '中刻是一番役牌' },
      rBakaze: { hand: '东东东123m456m789s55s', win: '2m', roundWind: 0, seatWind: 1, note: '东场，东风刻' },
      rJikaze: { hand: '南南南123m456m789s55s', win: '2m', roundWind: 0, seatWind: 1, note: '南家，南风刻' },
      rDora: { hand: '123m456m789m123s55s', win: '9m', dora: ['4m'], note: '宝牌指示牌 4 万，手里 5 万是宝牌' },
      rUraDora: { hand: '123m456m789m123s55s', win: '9m', flags: { riichi: true }, uraDora: ['4m'], note: '立直成功，里宝牌指示牌 4 万' },
      rRinshan: { hand: '234m567m789s99s', melds: [{ type: 'kan', tile: '1m' }], win: '9s', tsumo: true, flags: { rinshan: true }, note: '杠后补摸 9 条自摸' },
      rChankan: { hand: '123m456m789m123s55s', win: '9m', flags: { chankan: true }, note: '抢槓和牌' },
      rHaitei: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { haitei: true }, note: '海底自摸' },
      rHoutei: { hand: '123m456m789m123s55s', win: '9m', flags: { houtei: true }, note: '河底捞鱼' }
    }
  };

  DATA.sichuan = {
    title: '四川麻将（血战到底）',
    unit: '番',
    intro: '108 张，只有万、条、饼，缺一门才能和；番数是「翻倍次数」，例如 3 番就是 2³ = 8 倍。根（四张相同）每组加 1 番。',
    fans: [
      { name: '清十八罗汉', value: 7, ex: 'sQingShiba', desc: '清一色 + 十八罗汉（四副杠），翻倍次数最高。' },
      { name: '十八罗汉', value: 6, ex: 'sShiba', desc: '四副杠加一对将牌。' },
      { name: '清龙七对', value: 5, ex: 'sQingLongQiDui', desc: '清一色的龙七对：七对且有一组四张相同。' },
      { name: '天胡', value: 5, ex: 'sTianHu', desc: '庄家配牌后直接和牌。' },
      { name: '地胡', value: 5, ex: 'sDiHu', desc: '子家第一轮就胡别人打出的牌。' },
      { name: '清七对', value: 4, ex: 'sQingQiDui', desc: '清一色的七对。' },
      { name: '清带幺', value: 4, ex: 'sQingDaiYao', desc: '清一色且每副面子和将牌都带 1、9。' },
      { name: '清对', value: 3, ex: 'sQingDui', desc: '清一色的对对胡。' },
      { name: '龙七对', value: 3, ex: 'sLongQiDui', desc: '七对里有一组四张相同的牌（含暗杠）。' },
      { name: '清一色', value: 2, ex: 'sQingYiSe', desc: '整副牌只有一种花色。' },
      { name: '七对', value: 2, ex: 'sQiDui', desc: '七个对子。' },
      { name: '将对', value: 2, ex: 'sJiangDui', desc: '对对胡且全部由 2、5、8 组成。' },
      { name: '带幺九', value: 2, ex: 'sDaiYaoJiu', desc: '每副面子和将牌都带 1 或 9。' },
      { name: '对对胡', value: 1, ex: 'sDuiDuiHu', desc: '四副刻子（或杠）加一对将牌。' },
      { name: '金钩钓', value: 1, ex: 'sJinGouDiao', desc: '四副副露，单吊将牌和牌。' },
      { name: '杠上花', value: 1, ex: 'sGangShangHua', desc: '开杠后补摸的牌自摸和牌。' },
      { name: '抢杠胡', value: 1, ex: 'sQiangGangHu', desc: '和别家加杠的那张牌。' },
      { name: '海底捞月', value: 1, ex: 'sHaiDi', desc: '和牌墙上的最后一张牌。' },
      { name: '自摸', value: 1, ex: 'sZiMo', desc: '自己摸到和牌张（默认加番，可在条件里关掉）。' },
      { name: '平胡', value: 0, ex: 'sPingHu', desc: '基础牌型，不加番（1 倍）。' },
      { name: '根', value: 1, variable: true, valueText: '1/组', ex: 'sGen', desc: '四张相同的牌在同一副牌里（杠也算），每组加 1 番。' }
    ],
    examples: {
      sQingShiba: { hand: '2m2m', win: '2m', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '3m' }, { type: 'kan', tile: '5m' }, { type: 'kan', tile: '9m' }], note: '万子四副杠 + 2 万将' },
      sShiba: { hand: '5m5m', win: '5m', melds: [{ type: 'kan', tile: '1m' }, { type: 'kan', tile: '9m' }, { type: 'kan', tile: '2s' }, { type: 'kan', tile: '3s' }], note: '四副杠 + 5 万将' },
      sQingLongQiDui: { hand: '11112233445566m', win: '1m', note: '1 万四张 + 六对' },
      sTianHu: { hand: '123m456m789m123m55m', win: '9m', flags: { tenhou: true }, note: '配牌即和' },
      sDiHu: { hand: '123m456m789m123m55m', win: '9m', flags: { chiihou: true }, note: '第一轮胡牌' },
      sQingQiDui: { hand: '11223344556677m', win: '1m', note: '清一色七个对子' },
      sQingDaiYao: { hand: '111m123m789m789m99m', win: '7m', note: '每副面子和将牌都带 1、9，1 万和 9 万各四张还带根' },
      sQingDui: { hand: '111m333m555m777m99m', win: '1m', note: '清一色 + 四副刻子' },
      sLongQiDui: { hand: '1111m2233s4455p66p', win: '1m', note: '1 万四张 + 六对' },
      sQingYiSe: { hand: '123m456m789m123m55m', win: '9m', note: '只有万子' },
      sQiDui: { hand: '1122m3344m5566s77s', win: '1m', note: '七个对子' },
      sJiangDui: { hand: '222m555m888s222s55s', win: '2m', note: '全部由 2、5、8 组成的对对胡' },
      sDaiYaoJiu: { hand: '123m789m111s999s99m', win: '2m', note: '每副面子和将牌都带 1、9' },
      sDuiDuiHu: { hand: '111m333m555s777s99s', win: '1m', note: '四副刻子 + 99 条将' },
      sJinGouDiao: { hand: '99m', win: '9m', melds: [{ type: 'chi', tile: '1m' }, { type: 'pon', tile: '2m' }, { type: 'pon', tile: '5s' }, { type: 'pon', tile: '7s' }], note: '四副副露，单吊 9 万' },
      sGangShangHua: { hand: '234m567m789s99s', melds: [{ type: 'kan', tile: '1m' }], win: '9s', tsumo: true, flags: { rinshan: true }, note: '杠后补摸 9 条' },
      sQiangGangHu: { hand: '123m456m789m123m55m', win: '9m', flags: { chankan: true }, note: '抢杠胡' },
      sHaiDi: { hand: '123m456m789m123m55m', win: '9m', tsumo: true, flags: { haitei: true }, note: '最后一张牌和牌' },
      sZiMo: { hand: '123m456m789m123m55m', win: '9m', tsumo: true, note: '自摸' },
      sPingHu: { hand: '123m456m111s789s22m', win: '4m', note: '普通顺子牌型' },
      sGen: { hand: '111m123m456s789s55s', win: '2m', note: '四张 1 万，一组根' }
    }
  };

  DATA.guangdong = {
    title: '广东麻将（推倒胡）',
    unit: '番',
    intro: '常见推倒胡番表，番数相加，平胡 1 番起。各地牌馆差异较大，这里用最通行的一套。',
    fans: [
      { name: '十三幺', value: 13, ex: 'gShiSanYao', desc: '十三种幺九牌各一张，其中一种成对。' },
      { name: '大四喜', value: 13, ex: 'gDaSiXi', desc: '东南西北四副风牌刻子（或杠）齐全。' },
      { name: '天胡', value: 13, ex: 'gTianHu', desc: '庄家配牌后直接和牌。' },
      { name: '地胡', value: 13, ex: 'gDiHu', desc: '子家第一轮就胡牌。' },
      { name: '小四喜', value: 8, ex: 'gXiaoSiXi', desc: '三副风牌刻子，第四种风牌作将。' },
      { name: '大三元', value: 8, ex: 'gDaSanYuan', desc: '中、发、白三副刻子齐全。' },
      { name: '字一色', value: 8, ex: 'gZiYiSe', desc: '整副牌全部由字牌组成。' },
      { name: '清幺九', value: 8, ex: 'gQingYaoJiu', desc: '全部由序数牌 1、9 的刻子与将牌组成。' },
      { name: '清七对', value: 8, ex: 'gQingQiDui', desc: '清一色的七对。' },
      { name: '豪华七对', value: 8, ex: 'gHaoHuaQiDui', desc: '七对里有一组四张相同的牌。' },
      { name: '清碰', value: 8, ex: 'gQingPeng', desc: '清一色的碰碰胡。' },
      { name: '小三元', value: 5, ex: 'gXiaoSanYuan', desc: '中、发、白里有两副刻子，第三种作将。' },
      { name: '混幺九', value: 5, ex: 'gHunYaoJiu', desc: '全部由字牌和 1、9 的刻子与将牌组成。' },
      { name: '七对', value: 5, ex: 'gQiDui', desc: '七个对子。' },
      { name: '混碰', value: 5, ex: 'gHunPeng', desc: '混一色的碰碰胡。' },
      { name: '清一色', value: 5, ex: 'gQingYiSe', desc: '整副牌只有一种花色。' },
      { name: '混一色', value: 3, ex: 'gHunYiSe', desc: '一种花色的序数牌加字牌。' },
      { name: '碰碰胡', value: 2, ex: 'gPengPengHu', desc: '四副刻子（或杠）加一对将牌。' },
      { name: '平胡', value: 1, ex: 'gPingHu', desc: '普通顺子牌型，1 番起步。' },
      { name: '门前清', value: 1, ex: 'gMenQianQing', desc: '没有副露。' },
      { name: '自摸', value: 1, ex: 'gZiMo', desc: '自己摸到和牌张。' },
      { name: '杠上开花', value: 1, ex: 'gGangShangKaiHua', desc: '开杠后补摸的牌自摸和牌。' },
      { name: '抢杠胡', value: 1, ex: 'gQiangGangHu', desc: '和别家加杠的那张牌。' },
      { name: '海底捞月', value: 1, ex: 'gHaiDi', desc: '和最后一张牌。' },
      { name: '花牌', value: 1, variable: true, valueText: '1/张', ex: 'gHuaPai', desc: '每张花牌加 1 番。' }
    ],
    examples: {
      gShiSanYao: { hand: '19m19s19p东南西北中发白1m', win: '9m', note: '十三种幺九牌各一张' },
      gDaSiXi: { hand: '东东东南南南西西西北北北五万五万', win: '5m', note: '四副风刻' },
      gTianHu: { hand: '123m456m789m123s55s', win: '9m', flags: { tenhou: true }, note: '配牌即和' },
      gDiHu: { hand: '123m456m789m123s55s', win: '9m', flags: { chiihou: true }, note: '第一轮胡牌' },
      gXiaoSiXi: { hand: '东东东南南南西西西北北234m', win: '2m', note: '三副风刻，北作将' },
      gDaSanYuan: { hand: '中中中发发发白白白234m55s', win: '2m', note: '三副箭刻' },
      gZiYiSe: { hand: '东东东南南南西西西中中中发发', win: '东', note: '全字牌' },
      gQingYaoJiu: { hand: '111m999m111s999s99p', win: '1m', note: '全是 1、9 的刻子与将牌' },
      gQingQiDui: { hand: '11223344556677m', win: '1m', note: '清一色七个对子' },
      gHaoHuaQiDui: { hand: '1111m2233s4455p66p', win: '1m', note: '七对带一组四张' },
      gQingPeng: { hand: '111m333m555m777m99m', win: '1m', note: '清一色 + 四副刻子' },
      gXiaoSanYuan: { hand: '中中中发发发白白234m567s', win: '2m', note: '中、发刻子，白作将' },
      gHunYaoJiu: { hand: '111m999s中中中东东东白白', win: '东', note: '字牌与 1、9' },
      gQiDui: { hand: '1122m3344s5566p东东', win: '东', note: '七个对子' },
      gHunPeng: { hand: '111m333m555m中中中99m', win: '1m', note: '混一色 + 四副刻子' },
      gQingYiSe: { hand: '123m456m789m123m55m', win: '9m', note: '只有万子' },
      gHunYiSe: { hand: '123m456m789m中中中99m', win: '2m', note: '万子加字牌' },
      gPengPengHu: { hand: '111m333m555s777s99s', win: '1m', note: '四副刻子' },
      gPingHu: { hand: '123m456m789m123s55s', win: '9m', note: '普通顺子牌型' },
      gMenQianQing: { hand: '123m456m789m123m55m', win: '9m', note: '没有副露' },
      gZiMo: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, note: '自摸' },
      gGangShangKaiHua: { hand: '234m567m789s99s', melds: [{ type: 'kan', tile: '1m' }], win: '9s', tsumo: true, flags: { rinshan: true }, note: '杠后补摸和牌' },
      gQiangGangHu: { hand: '123m456m789m123s55s', win: '9m', flags: { chankan: true }, note: '抢杠胡' },
      gHaiDi: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { haitei: true }, note: '最后一张牌和牌' },
      gHuaPai: { hand: '123m456m789m123s55s', win: '9m', flowers: ['f1', 'f2'], note: '两张花牌' }
    }
  };

  DATA.taiwan = {
    title: '台湾麻将（十六张）',
    unit: '台',
    intro: '手牌 16 张、和牌 17 张（5 副面子 + 1 对将），台数相加，得分 = 底 + 台。花牌每张 1 台，正花再加 1 台，八仙过海（八张花全摸到）另加 8 台。',
    fans: [
      { name: '天胡', value: 24, ex: 'tTianHu', desc: '庄家配牌后直接和牌。' },
      { name: '大四喜', value: 16, ex: 'tDaSiXi', desc: '东南西北四副风牌刻子（或杠）齐全。' },
      { name: '字一色', value: 16, ex: 'tZiYiSe', desc: '整副牌全部由字牌组成。' },
      { name: '地胡', value: 16, ex: 'tDiHu', desc: '子家第一轮就胡牌。' },
      { name: '小四喜', value: 8, ex: 'tXiaoSiXi', desc: '三副风牌刻子，第四种风牌作将。' },
      { name: '大三元', value: 8, ex: 'tDaSanYuan', desc: '中、发、白三副刻子齐全。' },
      { name: '清一色', value: 8, ex: 'tQingYiSe', desc: '整副牌只有一种花色。' },
      { name: '五暗刻', value: 8, ex: 'tWuAnKe', desc: '五副暗刻（或暗杠）。' },
      { name: '八仙过海', value: 8, ex: 'tBaXian', desc: '八张花牌全部摸到。' },
      { name: '七对', value: 7, ex: 'tQiDui', desc: '台湾七对：七个对子加一副刻子，共 17 张。' },
      { name: '四暗刻', value: 5, ex: 'tSiAnKe', desc: '四副暗刻（或暗杠）。' },
      { name: '小三元', value: 4, ex: 'tXiaoSanYuan', desc: '中、发、白里有两副刻子，第三种作将。' },
      { name: '混一色', value: 4, ex: 'tHunYiSe', desc: '一种花色的序数牌加字牌。' },
      { name: '碰碰胡', value: 4, ex: 'tPengPengHu', desc: '五副刻子（或杠）加一对将牌。' },
      { name: '三暗刻', value: 2, ex: 'tSanAnKe', desc: '三副暗刻（或暗杠）。' },
      { name: '平胡', value: 2, ex: 'tPingHu', desc: '五副顺子、没有字牌、没有花牌、不是自摸。' },
      { name: '门风', value: 1, alts: ['门风 东', '门风 南', '门风 西', '门风 北'], ex: 'tMenFeng', desc: '自己门风（自风）的刻子，1 台。' },
      { name: '圈风', value: 1, alts: ['圈风 东', '圈风 南', '圈风 西', '圈风 北'], ex: 'tQuanFeng', desc: '当前圈风的刻子，1 台（与门风不同时另计）。' },
      { name: '三元牌', value: 1, alts: ['三元牌 红中', '三元牌 发财', '三元牌 白板'], ex: 'tSanYuanPai', desc: '中、发、白任意一种的刻子，1 台。' },
      { name: '花牌', value: 1, variable: true, valueText: '1/张', ex: 'tHuaPai', desc: '每张花牌 1 台。' },
      { name: '正花', value: 1, variable: true, valueText: '1/张', ex: 'tZhengHua', desc: '摸到自己门风对应的花（东家春夏/梅兰、南家夏兰/兰菊等），每张再加 1 台。' },
      { name: '门清', value: 1, ex: 'tMenQing', desc: '没有副露。' },
      { name: '自摸', value: 1, ex: 'tZiMo', desc: '自己摸到和牌张。' },
      { name: '杠上开花', value: 1, ex: 'tGangShangKaiHua', desc: '开杠后补摸的牌自摸和牌。' },
      { name: '抢杠胡', value: 1, ex: 'tQiangGangHu', desc: '和别家加杠的那张牌。' },
      { name: '海底捞月', value: 1, ex: 'tHaiDi', desc: '和最后一张牌。' },
      { name: '独听', value: 1, ex: 'tDuTing', desc: '只听一种牌（单吊、边张、坎张等）。' }
    ],
    examples: {
      tTianHu: { hand: '123m456m789m123s111p55s', win: '9m', tsumo: true, flags: { tenhou: true }, note: '配牌即和' },
      tDaSiXi: { hand: '东东东南南南西西西北北北中中中55m', win: '5m', note: '四副风刻 + 中刻' },
      tZiYiSe: { hand: '东东东南南南西西西北北北中中中发发', win: '东', note: '全字牌' },
      tDiHu: { hand: '123m456m789m123s111p55s', win: '9m', flags: { chiihou: true }, note: '第一轮胡牌' },
      tXiaoSiXi: { hand: '东东东南南南西西西北北中中中555m', win: '5m', note: '三副风刻，北作将' },
      tDaSanYuan: { hand: '中中中发发发白白白123m456m55s', win: '2m', note: '三副箭刻' },
      tQingYiSe: { hand: '123m456m789m234m555m88m', win: '9m', note: '只有万子' },
      tWuAnKe: { hand: '111m333m555m777m999m22m', win: '2m', note: '五副暗刻，和将牌' },
      tBaXian: { hand: '123m456m789m123s55s白白白', win: '白', flowers: ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8'], note: '八张花牌全摸到' },
      tQiDui: { hand: '111m2233445566s77p99p', win: '1m', note: '七对 + 一刻（1 万）' },
      tSiAnKe: { hand: '111m333m555m777m123s22s', win: '2s', note: '四副暗刻，和将牌' },
      tXiaoSanYuan: { hand: '中中中发发发白白123m456m789s', win: '白', note: '中、发刻子，白作将' },
      tHunYiSe: { hand: '123m456m789m中中中555m99m', win: '2m', note: '万子加字牌' },
      tPengPengHu: { hand: '111m333m555s777s999s11p', win: '1m', note: '五副刻子' },
      tSanAnKe: { hand: '111m333m555m123s456s22s', win: '2s', note: '三副暗刻' },
      tPingHu: { hand: '123m456m789m123s456s55s', win: '9m', note: '五副顺子、无字无花、非自摸' },
      tMenFeng: { hand: '东东东123m456m789m123s55s', win: '9m', seatWind: 0, roundWind: 1, note: '东家，东风刻' },
      tQuanFeng: { hand: '东东东123m456m789m123s55s', win: '9m', seatWind: 1, roundWind: 0, note: '东圈，东风刻' },
      tSanYuanPai: { hand: '中中中123m456m789m123s55s', win: '9m', note: '中刻 1 台' },
      tHuaPai: { hand: '123m456m789m123s55s白白白', win: '白', flowers: ['f1'], note: '摸到一张花牌' },
      tZhengHua: { hand: '123m456m789m123s55s白白白', win: '白', seatWind: 0, flowers: ['f1'], note: '东家摸到春，是正花' },
      tMenQing: { hand: '123m456m789m234m555m88m', win: '9m', note: '没有副露' },
      tZiMo: { hand: '123m456m789m123s111p55s', win: '9m', tsumo: true, note: '自摸' },
      tGangShangKaiHua: { hand: '234m567m789m123s55s', melds: [{ type: 'kan', tile: '1m' }], win: '9m', tsumo: true, flags: { rinshan: true }, note: '杠后补摸和牌' },
      tQiangGangHu: { hand: '123m456m789m234m555m88m', win: '9m', flags: { chankan: true }, note: '抢杠胡' },
      tHaiDi: { hand: '123m456m789m123s111p55s', win: '9m', tsumo: true, flags: { haitei: true }, note: '最后一张牌和牌' },
      tDuTing: { hand: '123m456m789m123s555s白白', win: '白', note: '单吊白板，只听这一种' }
    }
  };

  DATA.hongkong = {
    title: '香港麻将',
    unit: '番',
    intro: '新章番表：一番起糊，番型叠加，花牌与正花另计；一手牌数不出番型时按鸡胡（0 番）处理。',
    fans: [
      { name: '十三幺', value: 13, ex: 'hShiSanYao', desc: '十三种幺九牌各一张，其中一种成对。' },
      { name: '大四喜', value: 13, ex: 'hDaSiXi', desc: '东南西北四副风牌刻子（或杠）齐全。' },
      { name: '天胡', value: 13, ex: 'hTianHu', desc: '庄家配牌后直接和牌。' },
      { name: '地胡', value: 13, ex: 'hDiHu', desc: '子家第一轮就胡牌。' },
      { name: '字一色', value: 10, ex: 'hZiYiSe', desc: '整副牌全部由字牌组成。' },
      { name: '清幺九', value: 10, ex: 'hQingYaoJiu', desc: '全部由序数牌 1、9 的刻子与将牌组成。' },
      { name: '小四喜', value: 8, ex: 'hXiaoSiXi', desc: '三副风牌刻子，第四种风牌作将。' },
      { name: '大三元', value: 8, ex: 'hDaSanYuan', desc: '中、发、白三副刻子齐全。' },
      { name: '清一色', value: 7, ex: 'hQingYiSe', desc: '整副牌只有一种花色。' },
      { name: '小三元', value: 5, ex: 'hXiaoSanYuan', desc: '中、发、白里有两副刻子，第三种作将。' },
      { name: '混幺九', value: 5, ex: 'hHunYaoJiu', desc: '全部由字牌和 1、9 组成。' },
      { name: '七对', value: 3, ex: 'hQiDui', desc: '七个对子。' },
      { name: '混一色', value: 3, ex: 'hHunYiSe', desc: '一种花色的序数牌加字牌。' },
      { name: '碰碰胡', value: 3, ex: 'hPengPengHu', desc: '四副刻子（或杠）加一对将牌。' },
      { name: '平胡', value: 1, ex: 'hPingHu', desc: '四副顺子、没有字牌、没有花牌、不是自摸。' },
      { name: '门前清', value: 1, ex: 'hMenQianQing', desc: '没有副露。' },
      { name: '自摸', value: 1, ex: 'hZiMo', desc: '自己摸到和牌张。' },
      { name: '杠上开花', value: 1, ex: 'hGangShangKaiHua', desc: '开杠后补摸的牌自摸和牌。' },
      { name: '抢杠胡', value: 1, ex: 'hQiangGangHu', desc: '和别家加杠的那张牌。' },
      { name: '海底捞月', value: 1, ex: 'hHaiDi', desc: '和最后一张牌。' },
      { name: '花牌', value: 1, variable: true, valueText: '1/张', ex: 'hHuaPai', desc: '每张花牌 1 番。' },
      { name: '正花', value: 1, variable: true, valueText: '1/张', ex: 'hZhengHua', desc: '摸到自己门风对应的花，每张再加 1 番。' },
      { name: '无花', value: 1, ex: 'hWuHua', desc: '一张花牌都没有（可在条件里关掉）。' },
      { name: '鸡胡', value: 0, ex: 'hJiHu', desc: '数不出任何番型的和牌，按最低 0 番（1 番起糊则不能糊）处理。' }
    ],
    examples: {
      hShiSanYao: { hand: '19m19s19p东南西北中发白1m', win: '9m', note: '十三种幺九牌各一张' },
      hDaSiXi: { hand: '东东东南南南西西西北北北五万五万', win: '5m', note: '四副风刻' },
      hTianHu: { hand: '123m456m789m123s55s', win: '9m', flags: { tenhou: true }, note: '配牌即和' },
      hDiHu: { hand: '123m456m789m123s55s', win: '9m', flags: { chiihou: true }, note: '第一轮胡牌' },
      hZiYiSe: { hand: '东东东南南南西西西中中中发发', win: '东', note: '全字牌' },
      hQingYaoJiu: { hand: '111m999m111s999s99p', win: '1m', note: '全是 1、9 的刻子与将牌' },
      hXiaoSiXi: { hand: '东东东南南南西西西北北234m', win: '2m', note: '三副风刻，北作将' },
      hDaSanYuan: { hand: '中中中发发发白白白234m55s', win: '2m', note: '三副箭刻' },
      hQingYiSe: { hand: '123m456m789m123m55m', win: '9m', note: '只有万子' },
      hXiaoSanYuan: { hand: '中中中发发发白白234m567s', win: '2m', note: '中、发刻子，白作将' },
      hHunYaoJiu: { hand: '111m999s中中中东东东白白', win: '东', note: '字牌与 1、9' },
      hQiDui: { hand: '1122m3344s5566p东东', win: '东', note: '七个对子' },
      hHunYiSe: { hand: '123m456m789m中中中99m', win: '2m', note: '万子加字牌' },
      hPengPengHu: { hand: '111m333m555s777s99s', win: '1m', note: '四副刻子' },
      hPingHu: { hand: '123m456m789m123s55s', win: '9m', note: '四副顺子、无字无花、非自摸' },
      hMenQianQing: { hand: '123m456m789m123m55m', win: '9m', note: '没有副露' },
      hZiMo: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, note: '自摸' },
      hGangShangKaiHua: { hand: '234m567m789s99s', melds: [{ type: 'kan', tile: '1m' }], win: '9s', tsumo: true, flags: { rinshan: true }, note: '杠后补摸和牌' },
      hQiangGangHu: { hand: '123m456m789m123s55s', win: '9m', flags: { chankan: true }, note: '抢杠胡' },
      hHaiDi: { hand: '123m456m789m123s55s', win: '9m', tsumo: true, flags: { haitei: true }, note: '最后一张牌和牌' },
      hHuaPai: { hand: '123m456m789m123s55s', win: '9m', flowers: ['f1'], note: '一张花牌' },
      hZhengHua: { hand: '123m456m789m123s55s', win: '9m', seatWind: 0, flowers: ['f1'], note: '东家摸到春，是正花' },
      hWuHua: { hand: '123m456m789m123s55s', win: '9m', note: '一张花牌都没有' },
      hJiHu: { hand: '567m345s789p中中', melds: [{ type: 'chi', tile: '1m' }], win: '5m', opts: { wuHua: false }, note: '关掉「无花算 1 番」后，这副牌数不出番型，按鸡胡算' }
    }
  };

  global.MJ = global.MJ || {};
  global.MJ.Glossary = { data: DATA };
  if (typeof module !== 'undefined' && module.exports) module.exports = global.MJ.Glossary;
})(typeof window !== 'undefined' ? window : globalThis);
